name: CI - k6 binary with extensions

on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  K6_VERSION: v0.43.1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
          check-latest: true
          cache: true
      - run: |
          go mod download
          go generate ./...
      - uses: golangci/golangci-lint-action@v3
        continue-on-error: true
        with:
          version: v1.51.1
          args: --timeout 3m --verbose
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest
      - name: Build
        run: xk6 build --with github.com/szkiba/xk6-crypto=.
      - name: Test
        run: ./k6 run --no-usage-report test/crypto.test.js
  
  publish:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
          check-latest: true
          cache: true
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest
      - name: Build release
        run: .github/scripts/build-k6-release.sh ${{ github.ref_name }}
      - name: Push to s3
        working-directory: xk6-crypto
        run: aws s3 cp --recursive dist/ s3://${{ secrets.AWS_S3_ARTIFACTS_BUCKET }}/k6/
